export const getLoading = (state) => state.movies.loading;
export const getIsSearching = (state) => state.movies.isSearching;
export const getAllMovies = (state) => state.movies.movies;
export const getMovieDetail = (state) => state.movies.movieDetail;
export const getCastInfo = (state) => state.movies.castInfo;
export const getPersonDetail = (state) => state.movies.personDetail;
export const getSearchResult = (state) => state.movies.searchResult;
export const getUpcomingMovies = (state) => state.movies.upcomingMovies;
export const getTrailerVideos = (state) => state.movies.trailerVideos;
